language: cpp
sudo: required
dist: trusty

os: linux

env:
  global:
    - DISPLAY=:99

before_install:
  - chmod a+x ./ci/tests-environment.sh
  - ./ci/tests-environment.sh

before_script:
  - git fetch --unshallow

script:
 - chmod a+x ./ci/tests-ci.sh
 - ./ci/tests-ci.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  # quick fix for issue 223
  - if [ "$TRAVIS_TAG" != "$TRAVIS_BRANCH" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash ./upload.sh ./Embedded_IDE-*.AppImage ./Embedded_IDE-*.zip ./Embedded_IDE-*.tar.bz2

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
